# Generated by Django 4.2.1 on 2023-05-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='pin_id',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memo',
            name='room_id',
            field=models.IntegerField(default=0),
        ),
    ]
